// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNGtD4Oy1Qjez6XM0WeSSteTQR4xr5GqY',
    appId: '1:356447745839:web:238338d9955b356db113da',
    messagingSenderId: '356447745839',
    projectId: 'weatherapp-3c0b8',
    authDomain: 'weatherapp-3c0b8.firebaseapp.com',
    storageBucket: 'weatherapp-3c0b8.appspot.com',
    measurementId: 'G-LTTVBLZZ4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO4lvOwPmNio7FJf8YUH-wujdY34skrMk',
    appId: '1:356447745839:android:769f62f7f2b7c13fb113da',
    messagingSenderId: '356447745839',
    projectId: 'weatherapp-3c0b8',
    storageBucket: 'weatherapp-3c0b8.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNGtD4Oy1Qjez6XM0WeSSteTQR4xr5GqY',
    appId: '1:356447745839:web:901b60f7f6e777b6b113da',
    messagingSenderId: '356447745839',
    projectId: 'weatherapp-3c0b8',
    authDomain: 'weatherapp-3c0b8.firebaseapp.com',
    storageBucket: 'weatherapp-3c0b8.appspot.com',
    measurementId: 'G-X0EPHVZ9ER',
  );

}